version: '3'
services:
  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - "5672:5672"
      - "15672:15672"
      - "25672:25672"
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
  consul:
    image: consul:latest
    container_name: consul
    restart: always
    ports:
      - "8500:8500"
      - "8600:8600"
  dbproxy:
    build:
      context: ./dbproxy
    ports:
      - "10000:10000"

  account:
    build:
      context: ./account
    ports:
      - "10001:10001"

  file:
    build:
      context: ./file
    ports:
      - "9090:9090"

  transfer:
    build:
      context: ./transfer

  gateway:
    build:
      context: ./gateway
    ports:
      - "8080:8080"